name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies (default + dev)
        run: uv sync --all-extras --dev

      - name: Lint (ruff)
        run: uv run ruff check .

      - name: Run tests (pytest)
        run: uv run pytest -q


